sonar.sources=src,public
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.javascript.lcov.reportPaths=reports/unit-tests/coverage/lcov.info
sonar.coverage.exclusions=src/server.js,src/config/database.js,public/app.js
sonar.exclusions=node_modules/**,reports/**,outputs/**
sonar.sourceEncoding=UTF-8
